# Generated by Django 4.2 on 2023-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='photo_path',
            new_name='images',
        ),
    ]
