# Generated by Django 4.2 on 2023-05-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='varaint_value',
            new_name='variant_value',
        ),
    ]
