# Generated by Django 4.2 on 2023-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categoriess', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
