# Generated by Django 4.2 on 2023-04-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categories_options_alter_categories_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='url',
            new_name='slug',
        ),
    ]
