# Generated by Django 4.2 on 2023-04-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_url_categories_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'categoriess', 'verbose_name_plural': 'categories'},
        ),
    ]
